### DISCUSSION TITLE
docker socket integration

### DISCUSSION THREAD

**Discussion by bearded-papa** [fosrl/newt#59] [Q&A] [answered]
I have just updated to the latest version 1.5.0 and also updated newt but am unable to see any docker integration in the resourses section

**Comment by oschwartz10612** [comment]
We changed it to be opt in. Make sure you have `--docker-socket` on your newt and that it can access the socket. Also make sure it is enabled on the site when you create the site. With both of those you should see the button. Let me know if you do not.

**Reply by bearded-papa** [reply]
this is my newt docker-compose
```
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.<HIDDEN FOR SECURITY>
      - NEWT_ID=<HIDDEN FOR SECURITY>
      - NEWT_SECRET=<HIDDEN FOR SECURITY>
      - DOCKER_SOCKET=true
    networks:
      frontend: 
networks:
  frontend:
    external: true
```
I have then checked the site linked to this newt instance and the docker integration is enabled but nowhere can I find any refernce to the containers.

**Comment by bearded-papa** [comment, marked as answer]
Figured where my mistake was.
DOCKER_SOCKET variable needs to be = /var/run/docker.sock
so a full newt compose should be as follows for anyone else asking the same question
```
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.<HIDDEN FOR SECURITY>
      - NEWT_ID=<HIDDEN FOR SECURITY>
      - NEWT_SECRET=<HIDDEN FOR SECURITY>
      - DOCKER_SOCKET=/var/run/docker.sock
```
and there will be an orange link "View Docker Containers" under the IP section of Target Configuration when adding a new resource
