### ISSUE TITLE
Trouble with DNS in Docker Compose

### ISSUE THREAD

**Issue by jbcpollak** [fosrl/newt#34]
I'm trying to run newt in Docker on my Synology using their Container Manager. I created a docker compose like this:

```
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.tld
      - NEWT_ID=<newt_id>
      - NEWT_SECRET=<secret>
```

But the logs are full of the following:

```
ERROR: 2025/05/02 16:09:29 Failed to connect: failed to get token: failed to request new token: Post "https://pangolin.example.tld/api/v1/auth/newt/get-token": dial tcp: lookup pangolin.example.tld on 127.0.0.11:53: server misbehaving. Retrying in 10s...
```

When I run `docker exec -it newt nslookup pangolin.example.tld` I get a similar error:

```
:~$ sudo docker exec -it newt /bin/sh
/ # nslookup pangolin.example.tld
Server:		127.0.0.11
Address:	127.0.0.11:53

;; connection timed out; no servers could be reached

/ # cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

I'm not sure if this is a problem with the container image - maybe its a problem with Docker or the Synology Docker setup, but I wanted to ask if there anyone has any insight into this problem.

TIA.

**Comment by oschwartz10612** [comment]
Strange. Certainly seems for some reason it does not like the DNS. I cant fully tell you why this is occurring on Synology but what you could try is using the DNS env var to specify a DNS  and see if that helps. Let me know if it does or not.

**Comment by jbcpollak** [comment]
I tried setting DNS to 8.8.8.8 and 192.168.1.1 (my router) and in both cases I got the same error as above. _literally_ the same - the ip address of the server mentioned above didn't change. Which is very strange. And I did verify the container was rebuilt and running with the correct config. Its very strange.

```
services:
  newt:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.example.tld
      - NEWT_ID=<newt_id>
      - NEWT_SECRET=<secret>
      - DNS=8.8.8.8
```
